import { WalletButton } from '@/components/wagmi/Profile'
import { api } from '@/utils/api'
import { type NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: 'from tRPC' })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full items-center text-accent-orange-600">
        <div className="flex flex-col items-center">
          <h1 className="text-6xl font-bold">Welcome to T3</h1>
          <p className="mt-4 text-2xl">
            Get started by editing <code className="bg-background rounded-md p-2">pages/index.tsx</code>
          </p>
        </div>
        <WalletButton />
      </main>
    </>
  )
}

export default Home
