import { WalletButton } from '@/components/wagmi/Profile'
import { api } from '@/utils/api'
import { type NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: 'from tRPC' })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-full flex-col items-center">
        <nav className="sticky top-0 flex w-screen items-center justify-between py-4 pl-12 pr-4 text-primary">
          Ramen
          <WalletButton />
        </nav>
      </main>
    </>
  )
}

export default Home
